### ISSUE TITLE
ConRoc/helper.lua:788: attempt to index a nil value

### ISSUE THREAD

**Issue by rbpaiett** [Vae2009/ConROC_Rogue#1]
This error appeared when a change was made to the global ConROC file:

Message: Interface/AddOns/ConROC/helper.lua:788: attempt to index a nil value
Time: Thu Dec 12 12:35:33 2024
Count: 8
Stack: Interface/AddOns/ConROC/helper.lua:788: attempt to index a nil value
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC/helper.lua"]:788: in function `AbilityReady'
[string "@Interface/AddOns/ConROC_Rogue/rogue.lua"]:286: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1113: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConROC/buttons.lua"]:1875: in function `?'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

**Comment by Vae2009** [comment]
Rogue has not been updated to the current version yet.
